# @package training
num_epochs: 100
learning_rate: 0.00001
batch_size: null
save_directory: out
plot_frequency: 5
weight_by_system_size: true
early_stopping_patience: 20
target_property: bandgap
force_weight: 0.0
energy_weight: 1.0
bandgap_weight: 1.0
cutoff: 10.0
